cd data
wget http://data.csail.mit.edu/tofu/testset/vimeo_tri_test.zip
unzip vimeo_tri_test.zip
rm vimeo_tri_test.zip
wget http://data.csail.mit.edu/tofu/testset/vimeo_sep_noisy.zip
unzip vimeo_sep_noisy.zip
rm vimeo_sep_noisy.zip
wget http://data.csail.mit.edu/tofu/testset/vimeo_sep_blur.zip
unzip vimeo_sep_blur.zip
rm vimeo_sep_blur.zip
wget http://data.csail.mit.edu/tofu/testset/vimeo_sep_low.zip
unzip vimeo_sep_low.zip
rm vimeo_sep_low.zip
wget http://data.csail.mit.edu/tofu/testset/vimeo_sep_block.zip
unzip vimeo_sep_block.zip
rm vimeo_sep_block.zip
cd ..
